<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_ke 2</name>
   <tag></tag>
   <elementGuidId>acb0319f-7ea0-463f-9c38-f35c90444632</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='content']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>b1d9c272-cc21-44d6-9812-b98945c2ad23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>content</value>
      <webElementGuid>22cedc2d-d8a4-44e5-b9e0-d1a0a1c452f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>content</value>
      <webElementGuid>c0ed6f7a-fc05-46be-8422-a3a73534b82c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>AgroHome.aspx</value>
      <webElementGuid>5d332615-935d-4fce-8b10-15c187bd8bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>af390760-6c63-410e-b701-a86b1cd170ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>ab05d39c-43bd-46ae-9c59-015297d053e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>setIframeHeight(this.id); NProgress.done();</value>
      <webElementGuid>30d23d16-74ee-470f-ae9c-16a29d9346b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
			        &amp;amp;lt;p&amp;amp;gt;Browser anda tidak mendukung iframes.&amp;amp;lt;/p&amp;amp;gt;
		        </value>
      <webElementGuid>79bab294-80d2-4fae-bcf4-3d3c371d602a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)</value>
      <webElementGuid>3d092863-4d0f-4f4f-b92a-b2f93616016f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='content']</value>
      <webElementGuid>27e35c83-ade5-4b2a-a146-6b80f62a7261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/table/tbody/tr/td[2]/iframe</value>
      <webElementGuid>5cf7915a-a0f9-473e-bd6f-3cea8dcaa87f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ALT CS - MUSTIKA PUTRI NABILA'])[1]/following::iframe[2]</value>
      <webElementGuid>a928ab56-e581-4648-bd82-74ee70f1bd91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'content', '&quot;', ')')])[1]/preceding::iframe[1]</value>
      <webElementGuid>bde55dae-74c2-416a-a9e2-169454d15cba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/iframe</value>
      <webElementGuid>8052e88b-cac3-4553-a000-d33eb40d74b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'content' and @name = 'content' and @src = 'AgroHome.aspx' and (text() = '
			        &amp;amp;lt;p&amp;amp;gt;Browser anda tidak mendukung iframes.&amp;amp;lt;/p&amp;amp;gt;
		        ' or . = '
			        &amp;amp;lt;p&amp;amp;gt;Browser anda tidak mendukung iframes.&amp;amp;lt;/p&amp;amp;gt;
		        ')]</value>
      <webElementGuid>c7ae75c7-caac-4628-b5c7-6e2093721a62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
