<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_ke 1</name>
   <tag></tag>
   <elementGuidId>f5d22ee6-d23d-487c-8fce-ebb770aef098</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='menu']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>a4b671c2-c51c-4f77-8bf0-da0faa5a6ee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>4c1cda19-87e9-48ef-bd39-d79f5c357804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>d8588c56-64e9-4053-867b-98f999269a62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>Menu.aspx</value>
      <webElementGuid>206e667a-845e-4b1f-8eb0-2f67eb9e3621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>08a3546f-b030-4d6a-971b-562b0bed8272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>a586f238-e537-40b1-98c0-d68c404aa577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>setIframeHeight(this.id);</value>
      <webElementGuid>bc098662-b246-4abb-af19-d47d858e3845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
			        &amp;amp;lt;p&amp;amp;gt;Browser anda tidak mendukung iframes.&amp;amp;lt;/p&amp;amp;gt;
		        </value>
      <webElementGuid>c81e412c-136d-4ed0-9410-2c4f66950178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)</value>
      <webElementGuid>d7782a91-d45e-4cac-8f1b-b466e91368cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='menu']</value>
      <webElementGuid>5b58593f-e0ac-41b0-8cc9-bf8b603eca09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/table/tbody/tr/td/iframe</value>
      <webElementGuid>ebf5d256-41b3-4b2a-b0fd-437152e54d9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ALT CS - MUSTIKA PUTRI NABILA'])[1]/following::iframe[1]</value>
      <webElementGuid>b790fe35-9817-492b-821d-9af1c0e3f26d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='&amp;amp;lt;p&amp;amp;gt;Browser anda tidak mendukung iframes.&amp;amp;lt;/p&amp;amp;gt;']/parent::*</value>
      <webElementGuid>744ddd21-4b35-46f7-b4aa-8e8ec607c25b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>20e1b02a-008e-44b2-ae58-9cb0a78391fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'menu' and @name = 'menu' and @src = 'Menu.aspx' and (text() = '
			        &amp;amp;lt;p&amp;amp;gt;Browser anda tidak mendukung iframes.&amp;amp;lt;/p&amp;amp;gt;
		        ' or . = '
			        &amp;amp;lt;p&amp;amp;gt;Browser anda tidak mendukung iframes.&amp;amp;lt;/p&amp;amp;gt;
		        ')]</value>
      <webElementGuid>9d3ad8bb-28c4-4359-a508-c1a4783ebdaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
