<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnPrint</name>
   <tag></tag>
   <elementGuidId>dc5bf21c-d328-42a2-953c-b1f1ae94ef9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnPrint']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnPrint</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b931a519-2379-479b-ab49-55114ad27d49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ac55b1f8-9053-4c53-85c7-12d47359aadf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnPrint</value>
      <webElementGuid>ef073a0a-6fb1-4b0b-9619-102854e0304b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Cetak Data Statis</value>
      <webElementGuid>741af076-dc53-4368-a61f-d6eae762b81f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>ShowPopUp('http://172.31.1.93:9000//NONMONETARY/DataStatis.aspx', 4); return false;</value>
      <webElementGuid>cebc5937-aefb-4c8b-8e57-abedfff03737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnPrint</value>
      <webElementGuid>3ab0d0e3-a320-4547-ade6-678ac8a69ea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c5e79218-2da5-41a9-b352-3b97e160428f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnPrint&quot;)</value>
      <webElementGuid>2bf411d9-1335-4d64-b634-66721456265c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Mass Opening Upload/Page_DEV Agro Banking System/iframe_ke 2</value>
      <webElementGuid>611c2637-9e4c-4e47-b532-f048cce74bfd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnPrint']</value>
      <webElementGuid>4628330f-fad8-4d4f-9453-f249a4af8d02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div[3]/input[2]</value>
      <webElementGuid>96909731-de03-46ad-8ada-6f49be5fe8d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input[2]</value>
      <webElementGuid>39f0ebe0-a7bb-4cd2-a5e7-7f42bd6faa88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'btnPrint' and @id = 'btnPrint']</value>
      <webElementGuid>61d86622-21bf-4416-bf0c-49804f027d96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
