<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Sub Menu_Pembukaan Rekening Massal</name>
   <tag></tag>
   <elementGuidId>246614ec-4cf6-419e-a19a-d3a1d5021a31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;parent.loadFrame('http://172.31.1.93:9000//NONMONETARY/DD/MassAccountOpening.aspx');&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7fccf1b2-02d3-4978-a6b1-7287d1f10d34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>linkmenu</value>
      <webElementGuid>cf559138-34bf-441d-9121-15707cb95f10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>parent.loadFrame('http://172.31.1.93:9000//NONMONETARY/DD/MassAccountOpening.aspx');</value>
      <webElementGuid>7dfbe62a-de0d-43f3-92dc-6aa80730e02d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Pembukaan Rekening Massal dengan metode upload</value>
      <webElementGuid>a6762fa5-8210-4d87-8cd1-15597a12e5e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pembukaan Rekening Massal</value>
      <webElementGuid>4c182831-fc70-40f9-b0da-e380e373e6db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menucontainer&quot;)/table[@class=&quot;submenu&quot;]/tbody[1]/tr[1]/td[2]/a[@class=&quot;linkmenu&quot;]</value>
      <webElementGuid>96593727-2dab-47e0-b203-cee84e53cda4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Mass Opening Upload/Page_DEV Agro Banking System/iframe_ke 2</value>
      <webElementGuid>2ac03bef-9a0b-41a4-8903-164e5098dfd1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;parent.loadFrame('http://172.31.1.93:9000//NONMONETARY/DD/MassAccountOpening.aspx');&quot;]</value>
      <webElementGuid>e494e841-4e7d-4f43-bda6-12034e7ab8cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menucontainer']/table[17]/tbody/tr/td[2]/a</value>
      <webElementGuid>2103ddee-7eb7-46c5-b2fd-c4a7d9915a62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Pembukaan Rekening Massal')]</value>
      <webElementGuid>4b2bf456-0a0f-4650-bdb6-75daf76a67d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Print Bilyet Giro'])[1]/following::a[1]</value>
      <webElementGuid>d992eba1-013d-4fdb-a9fc-0194188a2085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pendaftaran SMS Notifikasi'])[1]/following::a[2]</value>
      <webElementGuid>3735e373-7bae-4080-8fd9-ee80bef07d8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pembukaan Rekening Massal']/parent::*</value>
      <webElementGuid>bd988e8d-7ab2-4bc5-9792-8b7055926814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[17]/tbody/tr/td[2]/a</value>
      <webElementGuid>202d3959-f26e-4571-8555-6c3abfaa7050</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Pembukaan Rekening Massal dengan metode upload' and (text() = 'Pembukaan Rekening Massal' or . = 'Pembukaan Rekening Massal')]</value>
      <webElementGuid>90f9cca0-20cd-49d9-b933-9fb6b991deeb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
