<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>halaman 2</name>
   <tag></tag>
   <elementGuidId>10cacff2-b1d9-4134-9451-30ab284ed75b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='gridUser']/tbody/tr[17]/td/table/tbody/tr/td[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bafc9597-1514-466b-9cc3-c613079055ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('gridUser','Page$2')</value>
      <webElementGuid>b5aa32b8-e64d-4cab-9b4c-46ce65c9849c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>d62bbf98-b50d-4234-a696-9ffbdfb1c883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gridUser&quot;)/tbody[1]/tr[@class=&quot;pager&quot;]/td[1]/table[1]/tbody[1]/tr[1]/td[2]/a[1]</value>
      <webElementGuid>9d543f5e-f9e8-4d9b-bc74-d0ee84efa480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Mass Opening Upload/SYS/iframe_ke 2</value>
      <webElementGuid>a13c9387-4109-4f5b-ad06-d157d82b1d79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gridUser']/tbody/tr[17]/td/table/tbody/tr/td[2]/a</value>
      <webElementGuid>74d92909-7e5f-4bc0-8202-8f294184eac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'2')]</value>
      <webElementGuid>1ec88bdc-5baa-45c4-82f6-992533e1f257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suspended'])[6]/following::a[1]</value>
      <webElementGuid>13ca072e-014b-4e5f-bbfd-8d814d6ef311</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='U'])[15]/following::a[1]</value>
      <webElementGuid>d0f0b33f-6d18-4f1b-8ec7-3a6c44143e1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset'])[1]/preceding::a[2]</value>
      <webElementGuid>77011e5a-d79b-451c-9816-c70fbf2789e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2']/parent::*</value>
      <webElementGuid>5d06452a-1679-4560-856d-cde133eeee42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('gridUser','Page$2')&quot;)]</value>
      <webElementGuid>bea941c4-fd8a-4fc7-b0c9-e648f9746433</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>cd07529f-c256-4452-9b90-bb32942b004c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;gridUser&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;Page$2&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = '2' or . = '2')]</value>
      <webElementGuid>7362bc24-6551-4ef5-9eaf-74f9b6467c4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
