<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_ke 1</name>
   <tag></tag>
   <elementGuidId>e3235252-db70-45f2-afca-a55545193c28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='menu']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>0f0fe008-bdb7-43a5-b964-f90a33110710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>6a16c635-c1f8-4ef9-9ad6-74c4bcde126d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>a924004b-a4df-4775-a2cd-f1f7c21a0fe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>Menu.aspx</value>
      <webElementGuid>4e406a53-3cf2-48f1-8036-3b65671675f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b975b8ce-10b8-431f-9fb7-625fbb0e90f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>20e4f798-f425-43aa-abbf-6d96161e666c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>setIframeHeight(this.id);</value>
      <webElementGuid>cfaec7e4-64bb-46ae-9e0e-4cded80bb067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
			        &amp;amp;lt;p&amp;amp;gt;Browser anda tidak mendukung iframes.&amp;amp;lt;/p&amp;amp;gt;
		        </value>
      <webElementGuid>344fab4d-9dae-48b2-8802-db77478ad19f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)</value>
      <webElementGuid>873e5e6f-62e2-4ac1-856b-e53452ab33ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='menu']</value>
      <webElementGuid>386ab49b-9c8d-4cf8-bf18-1d8b4516a80f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/table/tbody/tr/td/iframe</value>
      <webElementGuid>258ac2e8-4954-436d-b7c7-43df58721f58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administrator SYS'])[1]/following::iframe[1]</value>
      <webElementGuid>b7ab8a9b-9e1b-4288-8ef1-bf236c1d6c42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='&amp;amp;lt;p&amp;amp;gt;Browser anda tidak mendukung iframes.&amp;amp;lt;/p&amp;amp;gt;']/parent::*</value>
      <webElementGuid>534ca286-d74e-45b3-a44c-3ac16f3df7b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>9c8e5c5d-e916-4c58-a221-864b8016e013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'menu' and @name = 'menu' and @src = 'Menu.aspx' and (text() = '
			        &amp;amp;lt;p&amp;amp;gt;Browser anda tidak mendukung iframes.&amp;amp;lt;/p&amp;amp;gt;
		        ' or . = '
			        &amp;amp;lt;p&amp;amp;gt;Browser anda tidak mendukung iframes.&amp;amp;lt;/p&amp;amp;gt;
		        ')]</value>
      <webElementGuid>9f051fcd-d6c0-4887-a467-1cf51afdfe03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
