<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Pilih 4</name>
   <tag></tag>
   <elementGuidId>752db678-2758-41b2-a1b2-811921b61553</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='gridUser']/tbody/tr[5]/td/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8b6d0150-83a6-4310-9b8c-afb768869070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('gridUser','Select$3')</value>
      <webElementGuid>a4cc1aa3-7f3d-45fe-9819-4101b1a91c17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih</value>
      <webElementGuid>df0e6b3d-2d9a-48e1-a1f4-e9a20a35b10a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gridUser&quot;)/tbody[1]/tr[@class=&quot;r1&quot;]/td[1]/a[1]</value>
      <webElementGuid>5efd58ba-f5c4-4a19-8a71-39fdec8969f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Mass Opening Upload/SYS/Page_DEV Agro Banking System/iframe_ke 2</value>
      <webElementGuid>102c90c0-d32a-42dc-a90a-7fc751d1be3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gridUser']/tbody/tr[5]/td/a</value>
      <webElementGuid>53608c72-1286-46a7-ba78-86c3c4485351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Pilih')])[4]</value>
      <webElementGuid>7cae2a02-185e-4b24-bc3f-2c2795b6988c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Okay'])[3]/following::a[1]</value>
      <webElementGuid>da1673aa-081e-4140-a756-41a830f0dbf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='U'])[3]/following::a[1]</value>
      <webElementGuid>fabe4e58-bb79-4cee-bcc1-56cf2ea9808a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nita Kartika'])[1]/preceding::a[1]</value>
      <webElementGuid>2981ecbb-e4e9-4d65-88b6-8b5705ea8347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ALT PINCA/KABAG/WAKA'])[1]/preceding::a[1]</value>
      <webElementGuid>70ef741f-f3fd-42b9-a965-8c0301e05e5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('gridUser','Select$3')&quot;)]</value>
      <webElementGuid>31944d93-c2b1-4942-932d-f03e447fb5a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td/a</value>
      <webElementGuid>9418e86f-5eee-4ea3-b34f-d56cf8258d01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;gridUser&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;Select$3&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Pilih' or . = 'Pilih')]</value>
      <webElementGuid>bbd5fff7-12d7-4d46-9f7b-9ec77955cc81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
