<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Pilih 11</name>
   <tag></tag>
   <elementGuidId>90b68a79-2891-4c41-b1f1-67f18b03d165</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='gridUser']/tbody/tr[12]/td/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f4bd88b7-a2f9-458d-b9a2-3bf65263004d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('gridUser','Select$10')</value>
      <webElementGuid>cdfaaf09-4119-4117-8a53-d8115c72fa5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih</value>
      <webElementGuid>54635b10-8a17-4118-8493-131d8e2eb8e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gridUser&quot;)/tbody[1]/tr[12]/td[1]/a[1]</value>
      <webElementGuid>7e38b204-337e-4835-a4ee-600262100b8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Mass Opening Upload/SYS/Page_DEV Agro Banking System/iframe_ke 2</value>
      <webElementGuid>e28bf991-5fca-4da7-a9cf-adc2ba683853</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gridUser']/tbody/tr[12]/td/a</value>
      <webElementGuid>128b7239-977d-4384-97be-f65371e8ef5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Pilih')])[11]</value>
      <webElementGuid>17b6d7a3-a81e-4d77-a45a-07bf17ac52d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Okay'])[7]/following::a[1]</value>
      <webElementGuid>2d4c873c-fcb1-41f1-a306-f9154eee5ec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='U'])[10]/following::a[1]</value>
      <webElementGuid>603c09cd-26a2-41c8-af4d-bf4aa7471696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TELLER 2'])[1]/preceding::a[1]</value>
      <webElementGuid>5f05eb2d-e725-4ed3-8fcc-19b95af01c5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TELLER'])[2]/preceding::a[1]</value>
      <webElementGuid>d635f573-b311-4b1b-8a67-e66d54206982</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('gridUser','Select$10')&quot;)]</value>
      <webElementGuid>3760f210-2e04-493a-ae4c-4bc62f7a573c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[12]/td/a</value>
      <webElementGuid>2b459edf-f544-458a-b313-a95bb9a7fb23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;gridUser&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;Select$10&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Pilih' or . = 'Pilih')]</value>
      <webElementGuid>555e53ce-0d6e-440c-864a-3d18ee7871ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
