<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Pilih 7</name>
   <tag></tag>
   <elementGuidId>4ad7d0cb-8ad9-4e91-8032-61a272499f16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='gridUser']/tbody/tr[8]/td/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5f6d4b74-bc69-4294-b46d-570ee919f9c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('gridUser','Select$6')</value>
      <webElementGuid>b06b24d3-f20b-4bea-9e0a-e0b14c2c9279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih</value>
      <webElementGuid>ac0b2dfb-ff7b-44d7-a191-b30141ae3288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gridUser&quot;)/tbody[1]/tr[8]/td[1]/a[1]</value>
      <webElementGuid>efdb4a4e-3094-498b-ac24-b23f8290deae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Mass Opening Upload/SYS/Page_DEV Agro Banking System/iframe_ke 2</value>
      <webElementGuid>7ba1af67-4308-4060-b4ca-26e1f2bfd276</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gridUser']/tbody/tr[8]/td/a</value>
      <webElementGuid>b981e2dd-c24c-4566-bfdf-566330e276c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Pilih')])[7]</value>
      <webElementGuid>1e4f3048-15f2-4ff9-a7bc-cf24734fa570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expired'])[1]/following::a[1]</value>
      <webElementGuid>ccf995e4-9cd3-4eda-9908-4a2026fc9de7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='U'])[6]/following::a[1]</value>
      <webElementGuid>fd1270db-9f55-4d7b-99bb-c8bc0c4071b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ALT MOL'])[1]/preceding::a[1]</value>
      <webElementGuid>49a7fa75-b039-4d8b-9a50-660437d07f3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ALT MOL/SOL'])[1]/preceding::a[1]</value>
      <webElementGuid>c034a5ec-26de-4ccb-b2ab-01fa75c119f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('gridUser','Select$6')&quot;)]</value>
      <webElementGuid>ce96424c-29b0-42e5-9571-51d0a466fd30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td/a</value>
      <webElementGuid>5e60b960-3749-43ca-8f50-f497b6fb7946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;gridUser&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;Select$6&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Pilih' or . = 'Pilih')]</value>
      <webElementGuid>69e60d04-e3a6-467b-aa0b-52c10688ffda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
