<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Sub Pemeliharaan Pengguna v2</name>
   <tag></tag>
   <elementGuidId>b63a9b60-97e9-4427-adae-48b99e8b05a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;parent.loadFrame('http://172.31.1.93:9000//TELLERSYSTEM/ADMINISTRATION/UserProfileMaintenance2.aspx');&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0f3ad8ef-c9f4-41b1-9fc3-3a45e84ddc2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>linkmenu</value>
      <webElementGuid>70409331-e0f5-40a0-9e9a-4eeeec948500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>parent.loadFrame('http://172.31.1.93:9000//TELLERSYSTEM/ADMINISTRATION/UserProfileMaintenance2.aspx');</value>
      <webElementGuid>701129bc-25ef-48d7-a290-c8f23286de25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Menambah, Merubah, maupun Menghapus konfigurasi user yang ada di Unit Kerja bersangkutan</value>
      <webElementGuid>978734be-8b0a-404c-b9b1-011ccdcec7d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pemeliharaan Pengguna v2</value>
      <webElementGuid>5c611dca-9fd4-46c4-ac04-1f5b1d49d02a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menucontainer&quot;)/table[@class=&quot;submenu&quot;]/tbody[1]/tr[1]/td[2]/a[@class=&quot;linkmenu&quot;]</value>
      <webElementGuid>37aea3a8-452a-47a3-a153-8d3e8410406f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Mass Opening Upload/Page_DEV Agro Banking System/iframe_ke 2</value>
      <webElementGuid>a446bd17-19d5-466b-8151-0dcfbf4fd333</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;parent.loadFrame('http://172.31.1.93:9000//TELLERSYSTEM/ADMINISTRATION/UserProfileMaintenance2.aspx');&quot;]</value>
      <webElementGuid>a4e8ccde-0bfe-4f73-a363-43e740dc18bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menucontainer']/table[3]/tbody/tr/td[2]/a</value>
      <webElementGuid>133e5c66-8192-4afb-aee2-b109f9e4af68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Pemeliharaan Pengguna v2')]</value>
      <webElementGuid>bee4274e-761d-48c9-b9ad-21e280e311a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kode Unit Kerja'])[1]/following::a[1]</value>
      <webElementGuid>a07926d0-b1af-400b-b326-aac9d619dfc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Konfigurasi Unit Kerja'])[1]/following::a[2]</value>
      <webElementGuid>7f352ee7-0d2f-4632-9cfc-8fba3cb39dc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengaturan Limit Transaks...'])[1]/preceding::a[1]</value>
      <webElementGuid>5efbd7d6-4ca6-4f93-ad82-5e563f62967c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pemeliharaan Pengguna v2']/parent::*</value>
      <webElementGuid>4b38a56e-a5d7-4e79-b865-f394003445dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[3]/tbody/tr/td[2]/a</value>
      <webElementGuid>22910b99-bd01-46d9-baac-580c6955454b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Menambah, Merubah, maupun Menghapus konfigurasi user yang ada di Unit Kerja bersangkutan' and (text() = 'Pemeliharaan Pengguna v2' or . = 'Pemeliharaan Pengguna v2')]</value>
      <webElementGuid>fab9f2be-c649-4b11-8fe2-e0300bd82cd0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
