<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_1</name>
   <tag></tag>
   <elementGuidId>31103a31-f0b8-428b-bb59-0543ad682bfb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='gv']/tbody/tr[22]/td/table/tbody/tr/td/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bb3d07a0-c0cf-4938-af92-9ace05899b6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('gv','Page$1')</value>
      <webElementGuid>4bcec5f1-c87c-433a-8726-6d36e8065758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ebffcefb-6dec-4a89-a7e0-c2998c4cc062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gv&quot;)/tbody[1]/tr[22]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/a[1]</value>
      <webElementGuid>da48c1ac-24d8-468f-b2bf-20da168f7f6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Daftar Upload/Page_DEV Agro Banking System/iframe_ampltpampgtBrowser anda tidak menduk_ca06c4_1</value>
      <webElementGuid>2101f948-483a-4a96-85aa-ee0767b5295b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gv']/tbody/tr[22]/td/table/tbody/tr/td/a</value>
      <webElementGuid>768eff9a-f6c8-4620-bf98-2c3c976496be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'1')]</value>
      <webElementGuid>6f9130c8-5e75-4131-a165-a5a7cb5f1e32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Validasi Error'])[22]/following::a[1]</value>
      <webElementGuid>2e898dee-123e-409b-9eb5-0749ac9ed2a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E'])[20]/following::a[1]</value>
      <webElementGuid>be36c96d-64b7-4806-b696-13249002c202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'gv', '&quot;', ')/tbody[1]/tr[22]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/a[1]')])[1]/preceding::a[4]</value>
      <webElementGuid>e59bf5d6-6f08-4247-8b9f-923703997194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1']/parent::*</value>
      <webElementGuid>151a65fa-f3e5-478b-955d-d6655b4d00c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('gv','Page$1')&quot;)]</value>
      <webElementGuid>1cc64cf6-8259-4777-b1d5-d2ad7b08b1ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>1c70c63d-2450-4bbd-a5c5-bae0ccd0eefa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;gv&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;Page$1&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = '1' or . = '1')]</value>
      <webElementGuid>ce3b8c75-357a-4a05-9b3f-35dd41cbeec7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
