<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_2</name>
   <tag></tag>
   <elementGuidId>4f1bc1d9-4d9b-42d2-895a-7c4e86db5cb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='gv']/tbody/tr[22]/td/table/tbody/tr/td[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8823c847-ec5d-47d8-b4d4-1334942f26e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('gv','Page$2')</value>
      <webElementGuid>17654ea8-d88d-4501-8a50-2991491bec57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>0137dd93-8257-457c-83c1-970fa2f504a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gv&quot;)/tbody[1]/tr[22]/td[1]/table[1]/tbody[1]/tr[1]/td[2]/a[1]</value>
      <webElementGuid>2b18b77a-bc38-4011-b632-96374978bde9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Daftar Upload/Page_DEV Agro Banking System/iframe_ampltpampgtBrowser anda tidak menduk_ca06c4_1</value>
      <webElementGuid>2cbed6c2-819e-4fc6-8d69-1239b664977b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gv']/tbody/tr[22]/td/table/tbody/tr/td[2]/a</value>
      <webElementGuid>39df9ac6-cdd2-414c-a9fc-c4f8c85ee40b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'2')]</value>
      <webElementGuid>614cfd78-0ad9-4af9-9ca0-f69c7c6f8437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Identitas sudah dipakai oleh CIF lain'])[14]/following::a[1]</value>
      <webElementGuid>267eb5ed-9ff1-4077-901c-f912a667c09e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Validasi Error'])[22]/following::a[1]</value>
      <webElementGuid>2175d48c-747b-4287-b91c-164ec6dce230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'gv', '&quot;', ')/tbody[1]/tr[22]/td[1]/table[1]/tbody[1]/tr[1]/td[2]/a[1]')])[1]/preceding::a[4]</value>
      <webElementGuid>55a56a19-7fa5-4a78-b466-d84c7f314158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2']/parent::*</value>
      <webElementGuid>80710e4f-0269-4851-a4cd-cd3f4d6d6846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('gv','Page$2')&quot;)]</value>
      <webElementGuid>355c6809-e15b-469d-8159-6a09fcda2933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>ee8a1e8c-f4e7-4a5a-9317-5d927d95ce25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;gv&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;Page$2&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = '2' or . = '2')]</value>
      <webElementGuid>8341f35b-cf05-43a2-b4af-e28b873d9689</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
