<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Daftar Upload</name>
   <tag></tag>
   <elementGuidId>a92c660f-d031-4df5-a7de-cce773571bbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnStatus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btnStatus']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>eac1f499-5eb5-4a4c-953c-518779d7a972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnStatus</value>
      <webElementGuid>7aa36730-39d6-4c2b-b388-77ca03421e9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>main-button</value>
      <webElementGuid>0a53f663-ce7d-4abe-ac01-beba41101603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('btnStatus','')</value>
      <webElementGuid>236741a0-c9bc-424f-a3a6-bbd148fac642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar Upload</value>
      <webElementGuid>f9f325d5-4c16-401d-bc00-a82fff4bcfc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnStatus&quot;)</value>
      <webElementGuid>5b8ec63f-4748-4eeb-b45e-fc8453551890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Daftar Upload/Page_DEV Agro Banking System/iframe_ampltpampgtBrowser anda tidak menduk_ca06c4_1</value>
      <webElementGuid>12ba3465-717b-410f-b020-fc3c78d3614b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btnStatus']</value>
      <webElementGuid>c07526f9-4dfc-4335-a7e8-82ba63d2453c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/a[2]</value>
      <webElementGuid>66229b8d-512d-4874-aa8d-e6c8acdd91ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Daftar Upload')]</value>
      <webElementGuid>7cabef75-6139-400f-a600-fcbc952602c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload Baru'])[1]/following::a[1]</value>
      <webElementGuid>29f6f33a-8421-40ea-be4e-c0a974cfb230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mass Account Opening'])[2]/following::a[2]</value>
      <webElementGuid>12106ae0-36e8-4a32-90fc-595f1180dd1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'btnStatus', '&quot;', ')')])[1]/preceding::a[1]</value>
      <webElementGuid>6dbf48bb-726e-47c4-b52a-def3b5303adf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Daftar Upload']/parent::*</value>
      <webElementGuid>1078701f-9d49-4170-801d-119135fa0742</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('btnStatus','')&quot;)]</value>
      <webElementGuid>975b37df-fef9-4495-8a06-053d63918db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>a2e59429-5d48-4d78-80a3-120bbf7ec72d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btnStatus' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;btnStatus&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Daftar Upload' or . = 'Daftar Upload')]</value>
      <webElementGuid>6da9b6a5-9cb7-4a2f-9b07-2bc8bc04f651</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
