<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Logout</name>
   <tag></tag>
   <elementGuidId>2a7a0b0b-90ec-4c70-8795-f93ff8ab976d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Keluar dari Aplikasi&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;window.top.location = 'Logout.aspx';&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7d860616-1edc-46a7-a81f-36812a7a3ab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>window.top.location = 'Logout.aspx';</value>
      <webElementGuid>cd371801-e395-42d9-864b-da7187fb196e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Keluar dari Aplikasi</value>
      <webElementGuid>fa07e9db-3727-4f40-af77-342cf485d862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>aa8a372f-765f-48f2-b037-11c11a4a0341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu1&quot;)/li[4]/a[1]</value>
      <webElementGuid>a275418e-5e2a-4015-9173-0d62bfaf9041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Daftar Upload/Page_DEV Agro Banking System/iframe_ampltpampgtBrowser anda tidak menduk_ca06c4</value>
      <webElementGuid>fa2c3186-bb52-42f4-ae5d-08aa3331221b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;window.top.location = 'Logout.aspx';&quot;]</value>
      <webElementGuid>1fde1d39-6dc3-4899-b4bf-bd432c2a89d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='menu1']/li[4]/a</value>
      <webElementGuid>d604bcf3-95b7-41d6-a254-02741e3ed200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Logout')]</value>
      <webElementGuid>ee0c03ba-c08f-4096-b942-6d2f267d1a93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Migration'])[1]/following::a[1]</value>
      <webElementGuid>6ed35a7f-5b94-4222-8f6b-776317ae79f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='General'])[1]/following::a[2]</value>
      <webElementGuid>c14f5706-1682-46cb-a264-a5be7d7e11d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'menu1', '&quot;', ')/li[4]/a[1]')])[1]/preceding::a[1]</value>
      <webElementGuid>d8ebc46c-ba9d-4120-b5c1-ada54627fc32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Logout']/parent::*</value>
      <webElementGuid>4b5ff242-7138-4336-bf90-07f361deca21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>bb54e06a-a3b8-4822-8fc8-4baaa615122b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Keluar dari Aplikasi' and (text() = 'Logout' or . = 'Logout')]</value>
      <webElementGuid>cbaa9dd1-47e5-459a-aa1e-b825bf1cb420</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
