<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pembukaan Rekening Massal</name>
   <tag></tag>
   <elementGuidId>fe6df367-84c0-4515-a739-1020c12a6e05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;parent.loadFrame('http://172.31.1.93:9000//NONMONETARY/DD/MassAccountOpening.aspx');&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1abafa76-eaaf-4093-843c-c1f0e2f85456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>linkmenu</value>
      <webElementGuid>e9011d97-2c71-4419-abd9-17fd54604263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>parent.loadFrame('http://172.31.1.93:9000//NONMONETARY/DD/MassAccountOpening.aspx');</value>
      <webElementGuid>f066da17-a694-4a80-82ea-1d94345423d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Pembukaan Rekening Massal dengan metode upload</value>
      <webElementGuid>70976030-c3fa-4659-a74e-9bcf97d9ad10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pembukaan Rekening Massal</value>
      <webElementGuid>cf111ba0-1b46-4d6f-ab87-76d2835a1298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menucontainer&quot;)/table[@class=&quot;submenu&quot;]/tbody[1]/tr[1]/td[2]/a[@class=&quot;linkmenu&quot;]</value>
      <webElementGuid>6d01bf56-3ff2-4d2c-b78b-4228bdf9fe0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Daftar Upload/Page_DEV Agro Banking System/iframe_ampltpampgtBrowser anda tidak menduk_ca06c4_1</value>
      <webElementGuid>5323a017-36ed-4619-9125-408de64915a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;parent.loadFrame('http://172.31.1.93:9000//NONMONETARY/DD/MassAccountOpening.aspx');&quot;]</value>
      <webElementGuid>d46ff3b3-df65-4d47-b7fe-0846fa775618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menucontainer']/table[17]/tbody/tr/td[2]/a</value>
      <webElementGuid>fa51c662-ed32-4b24-861f-f5d51f57385a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Pembukaan Rekening Massal')]</value>
      <webElementGuid>2bc92406-5449-4f75-bd16-2a532f324156</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Print Bilyet Giro'])[1]/following::a[1]</value>
      <webElementGuid>83ae90b5-9fd0-49e8-9fdf-ff9b29d28905</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pendaftaran SMS Notifikasi'])[1]/following::a[2]</value>
      <webElementGuid>cbc9ae3c-3833-41cf-8e1c-fa9c451e78a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pembukaan Rekening Massal']/parent::*</value>
      <webElementGuid>b83e9fb5-3aa2-467e-95c6-8c4666910da6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[17]/tbody/tr/td[2]/a</value>
      <webElementGuid>2fa635f4-8d43-47a6-9305-44bfcba4f1af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Pembukaan Rekening Massal dengan metode upload' and (text() = 'Pembukaan Rekening Massal' or . = 'Pembukaan Rekening Massal')]</value>
      <webElementGuid>c36e70ef-a4da-4347-9671-4a15d4f9993e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
