<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_ampltpampgtBrowser anda tidak menduk_ca06c4</name>
   <tag></tag>
   <elementGuidId>80f2f315-e0d8-4fcf-a40b-3987767c5141</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='menu']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>211d0304-a9bf-4269-a245-1dd528978f0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>e080374e-8490-4ae1-af91-135b0907b36e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>9ca2b251-edd8-490e-941f-665bf6489680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>Menu.aspx</value>
      <webElementGuid>6a391673-eeeb-43e4-91ea-42d1a1b220e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>12c0f6af-2f44-4cc4-851f-0cc1d05144d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>2dbb5f60-79f1-4a00-9e38-ddf031155e95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>setIframeHeight(this.id);</value>
      <webElementGuid>76327ce9-e0f9-4bc2-8917-1c0a54256601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
			        &amp;amp;lt;p&amp;amp;gt;Browser anda tidak mendukung iframes.&amp;amp;lt;/p&amp;amp;gt;
		        </value>
      <webElementGuid>76854376-6da2-407d-a37d-ec59fdc4ec3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)</value>
      <webElementGuid>1c3ce361-5a1e-4772-b8e8-6fcf4316065c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='menu']</value>
      <webElementGuid>ee8ab605-fee5-45b9-91a2-2876100e36b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/table/tbody/tr/td/iframe</value>
      <webElementGuid>d9fc958d-07cf-497e-a02d-493013103981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ALT CS - MUSTIKA PUTRI NABILA'])[1]/following::iframe[1]</value>
      <webElementGuid>23ccf8ee-175b-48c2-91e6-0706be5532e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='&amp;amp;lt;p&amp;amp;gt;Browser anda tidak mendukung iframes.&amp;amp;lt;/p&amp;amp;gt;']/parent::*</value>
      <webElementGuid>27eaf4a2-aa40-415c-b158-b2d730c764c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>bb4f9440-509a-4764-bbb4-e8266876c238</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'menu' and @name = 'menu' and @src = 'Menu.aspx' and (text() = '
			        &amp;amp;lt;p&amp;amp;gt;Browser anda tidak mendukung iframes.&amp;amp;lt;/p&amp;amp;gt;
		        ' or . = '
			        &amp;amp;lt;p&amp;amp;gt;Browser anda tidak mendukung iframes.&amp;amp;lt;/p&amp;amp;gt;
		        ')]</value>
      <webElementGuid>39fcbacd-588b-4cc2-8a18-d29653e1fd20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
