<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__txtTanggal</name>
   <tag></tag>
   <elementGuidId>231669d1-fc85-4ae7-9021-f5f42a4019fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtTanggal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtTanggal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f4f137aa-b5ab-4076-9e64-92883b952dbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtTanggal</value>
      <webElementGuid>71971961-d7f7-4bf3-95c5-489901d0ae67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f5d83cc0-fadf-4408-ba10-f63ed868cb33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>26/05/2022</value>
      <webElementGuid>50b917f6-feff-431b-b5eb-4671cde028d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtTanggal</value>
      <webElementGuid>7be95b26-16a9-47cd-8b32-0b5a62692cc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt hasDatepicker</value>
      <webElementGuid>27c019c3-72aa-47ce-a8d7-fd54dcfa9727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtTanggal&quot;)</value>
      <webElementGuid>d5885c5b-2cec-4608-b807-2ee32aa5b129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Daftar Upload/Page_DEV Agro Banking System/iframe_ampltpampgtBrowser anda tidak menduk_ca06c4_1</value>
      <webElementGuid>4bddb4ea-7da1-417f-8e7e-ddad2aac91d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtTanggal']</value>
      <webElementGuid>736bf4ac-276f-4c99-9f9d-9991a12c44ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/table/tbody/tr/td[6]/input</value>
      <webElementGuid>fa0a9cf9-a821-4c76-8706-f4525e51a83e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/input</value>
      <webElementGuid>7f834ff9-65bb-4394-8d0a-bf7086644bb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtTanggal' and @type = 'text' and @id = 'txtTanggal']</value>
      <webElementGuid>03c9cce8-e7ea-4d2e-9804-fb9efaedf7d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
