<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__btnView</name>
   <tag></tag>
   <elementGuidId>f6c37fab-4a9c-4b24-a094-e45cb0f587f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnView</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnView']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>14d29603-cbe7-415a-948d-6d947872f4a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d0c27b39-d3fb-4838-9e55-5d527b6321c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnView</value>
      <webElementGuid>7113ec3a-4594-4015-8fa5-30d2533878ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>View</value>
      <webElementGuid>7eddc61f-1f73-4795-8c51-6e96a3323fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnView</value>
      <webElementGuid>165a6b13-f4c0-41e5-8af4-ad2ce01649b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9966414c-e8bb-43eb-98c1-9437e264eaea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnView&quot;)</value>
      <webElementGuid>e51b99f0-d4be-4cf0-8c44-be100e7c7c97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Daftar Upload/Page_DEV Agro Banking System/iframe_ampltpampgtBrowser anda tidak menduk_ca06c4_1</value>
      <webElementGuid>fc9646cd-fc60-4ccf-a01b-63b132ff79a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnView']</value>
      <webElementGuid>03193b07-e34e-4dc3-b17e-3ad29de3b1d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/table/tbody/tr[3]/td[7]/input</value>
      <webElementGuid>e1bb6bb7-460b-49a6-a6c5-c42b5531f07e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/input</value>
      <webElementGuid>6e77ca28-5773-416d-a82b-e776029eae2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'btnView' and @id = 'btnView']</value>
      <webElementGuid>5bd0f891-7dc5-4acc-95c8-f09d604e57ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
