<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_1</name>
   <tag></tag>
   <elementGuidId>d79aca6a-e539-4c23-85a3-be9f69886785</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td > table > tbody > tr > td</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='gv']/tbody/tr[22]/td/table/tbody/tr/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>c802ea43-d59f-44e0-85ee-e8cd1a5debdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>bb745f1b-36d8-4d5d-98e3-6ec18ce5b752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gv&quot;)/tbody[1]/tr[22]/td[1]/table[1]/tbody[1]/tr[1]/td[1]</value>
      <webElementGuid>5d2418e2-e75f-4089-ad52-b673d0cc73b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Daftar Upload/Page_DEV Agro Banking System/iframe_ampltpampgtBrowser anda tidak menduk_ca06c4_1</value>
      <webElementGuid>66cb5241-e60d-4e4d-be6a-f457f79b0cc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gv']/tbody/tr[22]/td/table/tbody/tr/td</value>
      <webElementGuid>7cc44a5f-b3c5-42f9-9704-e2016091f1d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Validasi Error'])[22]/following::td[5]</value>
      <webElementGuid>9422c493-4fe8-4a8d-8fc8-45f2060a0128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E'])[20]/following::td[7]</value>
      <webElementGuid>cb5e7bda-c02a-4c5c-8205-fa60f72435e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'gv', '&quot;', ')/tbody[1]/tr[22]/td[1]/table[1]/tbody[1]/tr[1]/td[1]')])[1]/preceding::td[5]</value>
      <webElementGuid>1694a4ba-a342-4f39-b30b-a42a8b27d3ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr/td</value>
      <webElementGuid>12c9b68f-95c5-4418-9ecc-c93aea30a59f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '1' or . = '1')]</value>
      <webElementGuid>9fbcdadd-5f11-48c3-8f7a-bb34941a7f05</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
