<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnReject</name>
   <tag></tag>
   <elementGuidId>c148a361-6c8b-4593-acc1-9b84b6324710</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnReject</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnReject']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>45cdd7ba-3ef1-4e42-b5bb-57e12bf92f58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>a6c8f608-311e-4af4-9d2e-ed4a7514f43e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnReject</value>
      <webElementGuid>be2bef9a-b7e2-4d4d-9828-41dd58e2238e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Reject</value>
      <webElementGuid>429a5e0f-7593-43f3-851c-93dbbff415d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnReject</value>
      <webElementGuid>4e1ed29d-d966-4a02-be42-80f4fdbf1774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>962527d4-c67f-4bf0-b175-e98d6d0258a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnReject&quot;)</value>
      <webElementGuid>27f127af-9eb4-4acf-bbd4-a60401f210f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/test test/Page_DEV Agro Banking System/iframe_reject</value>
      <webElementGuid>35ef8443-bb37-4d25-947f-fa2e910ca016</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnReject']</value>
      <webElementGuid>6e5a7a7f-e741-4115-84f3-dfb63bef43f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div[5]/input[2]</value>
      <webElementGuid>eaae949c-0dbf-4cef-925f-97b81b9363df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input[2]</value>
      <webElementGuid>a671bea3-ab1d-409d-9bd1-a96332c24cef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'btnReject' and @id = 'btnReject']</value>
      <webElementGuid>449e5f22-147a-45cf-9979-d8a999a68fb2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
