<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>detail</name>
   <tag></tag>
   <elementGuidId>df66675a-989e-48ab-a6e6-fce78042dcf5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Detail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.showdetail.button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>359a2e6c-e112-473a-bc88-737207e6141c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>52fc247f-fe5f-45b3-b69a-9f69bf689da5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Detail</value>
      <webElementGuid>ac481ff4-a93e-469d-9584-b782e0b6106b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:__doPostBack('gridPending','detail$0')</value>
      <webElementGuid>35399da9-d437-4b30-9400-d4be9f548f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>showdetail button</value>
      <webElementGuid>63578931-4f7d-41b4-bd21-9667ce68f682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gridPending&quot;)/tbody[1]/tr[2]/td[7]/input[@class=&quot;showdetail button&quot;]</value>
      <webElementGuid>144e1104-c525-4bb0-91cd-2c1b972316bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Mass Opening SPV/Approve SPV/iframe_ke 2</value>
      <webElementGuid>539678f6-2383-4ace-ad20-0e6b2fda42d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Detail']</value>
      <webElementGuid>051f07c0-b18f-4e37-9c31-3b1cd3e12db2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='gridPending']/tbody/tr[2]/td[7]/input</value>
      <webElementGuid>b11b7477-2be9-4862-b04c-a4b3b54640e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/input</value>
      <webElementGuid>86fe58f0-d35d-40f4-b209-f36d6be37032</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>27654e5d-7e75-4ec8-a295-735ff88d3c4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
