<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_NAMAKODE</name>
   <tag></tag>
   <elementGuidId>ee123cf9-e26e-455a-aa48-0e0e58e6ad10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='pilih']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pilih</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>34b9af73-c706-476c-b662-1b22a5d58653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pilih</value>
      <webElementGuid>b3fa6bc9-0f5a-4236-b74a-62d2ceb2481b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pilih</value>
      <webElementGuid>3cca1e1a-8030-4c8c-814b-e75d753c3ae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt</value>
      <webElementGuid>15ae1bf2-775b-4f07-affe-7842b7f7143a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
	NAMA
	KODE

</value>
      <webElementGuid>179a30ba-6338-4913-92a6-55d6afa47dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pilih&quot;)</value>
      <webElementGuid>986d930a-a2d2-46e1-af85-8446d6f4fced</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='pilih']</value>
      <webElementGuid>c9a1b9fb-7b1f-4493-b2b2-646c20aba035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/table/tbody/tr/td[2]/select</value>
      <webElementGuid>27538815-7fd3-46ea-ba9f-f6493dc14513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kriteria'])[1]/following::select[1]</value>
      <webElementGuid>88721e28-7fac-4669-a80d-1e7e0b5aabd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PENCARIAN KODE KARYAWAN'])[1]/following::select[1]</value>
      <webElementGuid>89b0efc2-b84b-442e-8757-2f97d8283995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kata Kunci'])[1]/preceding::select[1]</value>
      <webElementGuid>56f674ce-7c19-44b7-8863-1c05de80ae54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[1]/preceding::select[1]</value>
      <webElementGuid>1aa224bf-b80d-4a2d-9ad0-45bd1d64b146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>dc6678aa-8954-440e-b79a-6950383fd836</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'pilih' and @id = 'pilih' and (text() = '
	NAMA
	KODE

' or . = '
	NAMA
	KODE

')]</value>
      <webElementGuid>ea3f1450-d9ff-4ca9-a170-eedeffc71d0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
