<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__txtTanggalLahir</name>
   <tag></tag>
   <elementGuidId>68087fbc-c5aa-4a70-ba56-a754c910706d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtTanggalLahir']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtTanggalLahir</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>64eb54ad-0c2b-41cf-a450-b776393f6bf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtTanggalLahir</value>
      <webElementGuid>fd857b7c-f63c-48b3-9a7e-7ccde3adcdc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>10d78161-db75-425f-ab92-7c4678cdd036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtTanggalLahir</value>
      <webElementGuid>002ed076-4e03-4b2c-95bf-018dc5dceb2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd/MM/yyyy</value>
      <webElementGuid>a6c2ae20-f2cf-4ed0-a13c-6ad7386ebd4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt</value>
      <webElementGuid>4b64758f-1271-422c-88b5-800a09ceef49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtTanggalLahir&quot;)</value>
      <webElementGuid>0ece0fff-58c3-4e96-bbc2-82321a990953</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtTanggalLahir']</value>
      <webElementGuid>efe94ddf-44db-4ba6-82b7-291391f4a728</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/table/tbody/tr[3]/td[6]/input</value>
      <webElementGuid>19cf46e5-160a-4426-bba9-ee4f94872db5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[6]/input</value>
      <webElementGuid>08d1d30f-d0ed-407b-acb0-e9cc0d091037</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'txtTanggalLahir' and @type = 'text' and @id = 'txtTanggalLahir' and @placeholder = 'dd/MM/yyyy']</value>
      <webElementGuid>4ed6fc6c-0f69-4235-bd0c-4db9d3d73680</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
